name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # setiap 12 jam
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Cenzer0
          outputs: |
            dist/snake.svg

      - name: Commit & Push
        run: |
          mkdir -p output
          cp dist/snake.svg output/snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update snake" || echo "no changes"
          git push
